### ISSUE TITLE
Espais al final de la frase

### ISSUE THREAD

**Issue by jordimas** [aoliverg/MTUOC-novaIEC#2]
Hola,

Si tens una frase que diu 

"Hola amic "

la converteix a 

"Hola amic"

L'impacte és que quan fas un DIFF llavors mostra molts canvis per això (en els meus corpus). Llavors, estaria bé que el programa és limités a fer els canvis necessaris. 

Pensa que algunes interfícies d'usuaris hi ha cadenes com "Status: " on si treus l'espai després queda tot enganxat quan executes el programa. Això que és una mala practica (ja que hauríen de fer servir CSS o similar pels posicionaments) és bastant comú.

**Comment by aoliverg** [comment]
Hola:

Sí, eliminava tots els espais a l'inici i al final de cada segment. Ara ja he fet per recuperar-los. 

Gràcies 

Antoni

**Comment by jordimas** [comment]
Moltes gràcies!!! No acaba de fer-ho bé. Et pujo un exemple. En aquest fitxer zip tens 3 fitxers:

* evolution.txt -> fitxer original
* evolution-nou.txt -> fitxer amb la nova ortografia
* evolution.diff -> Diferències entre els dos

Veuràs que al diff encara hi ha modificades cadenes simplement perquè han canviat els espais. Per mi, lo ideal seria que només el diff mostrés el que ha canviat per temes de nova gramàtica i es preservessin els espais.

[evolution.zip](https://github.com/aoliverg/MTUOC-novaIEC/files/5468822/evolution.zip)

Un exemple de perquè els espais són importants en el context de traducció:

#: ../src/addressbook/gui/widgets/ea-minicard.c:157
msgid "Contact List: "
msgstr "Llista de contactes: "

#: ../src/addressbook/gui/widgets/ea-minicard.c:158
msgid "Contact: "
msgstr "Contacte: "

**Comment by aoliverg** [comment]
Hola:

He fet una petita modificació i crec que ja està solucionat. He provat amb els teus arxius i ara les diferències són sobretot per normalització d'apòstrofs.

Prova i em dius.

Gràcies
