### ISSUE TITLE
Normalització de caràcters

### ISSUE THREAD

**Issue by jordimas** [aoliverg/MTUOC-novaIEC#3]
He vist que normalitzés aquests caràcters:

https://github.com/aoliverg/MTUOC-novaIEC/blob/master/modificaIEC.py#L37

En traduccions també m'he trobat sovint aquests altres que cal normalitzar per si els vols considerar:

https://github.com/Softcatala/translation-memory-tools/blob/master/src/terminology/corpus.py#L71

Són bastant comuns amb fitxers PO i tenen que veure en que hi ha més d'una manera d'expressar accents en Unicode.

**Comment by aoliverg** [comment]
Hola:

Sí, mai tinc en compte això i en alguns casos pot ser important. En comptes de reemplaçar cada possible caràcter he fet servir unicodedata.normalize, que crec que és equivalente, de la següent manera:

cat=unicodedata.normalize('NFC',cat)

Gràcies
