### ISSUE TITLE
Directori '__pycache__'

### ISSUE THREAD

**Issue by jordimas** [aoliverg/MTUOC-novaIEC#4]
Aquest directori no cal pujar-lo:

https://github.com/aoliverg/MTUOC-novaIEC/tree/master/__pycache__

Es generà cada cop i més cada cop que fas un DIFF òbviament canvia. Merci

**Comment by aoliverg** [comment]
Hola:

Sí, coses del dissabte al matí. Ho he fet amb presses i això és el que passa. Ara l'elimino.

Gràcies

**Comment by jordimas** [comment]
Corregit
